services:
  app_r_executor:
    image: afanlife/r-executor:1.0
    container_name: app_r_executor
    restart: always
    volumes:
      - .:/app
    ports:
      - 5000:5000
    command: ["python3", "app.py"]